name: Mirror repository

on:
  push:
    branches: [main, docker/back, docker/front]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Push mirror
        run: |
          git clone --mirror https://github.com/github.com/pierre54200/Dashboard.git  repo-mirror
          cd repo-mirror
          git push https://${{ secrets.MIRROR_TOKEN }}@github.com/EpitechPGE3-2026/G-WEB-500-NCY-5-1-dashboard-2.git